services:
  app_dev:
    container_name: '${CONTAINER_NAME}_dev'
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - '${CONTAINER_PORT_DEV:-8080}:8080'
    networks:
      - go_network_app
    depends_on:
      - app_postgres
      - app_redis

  app_prod:
    container_name: '${CONTAINER_NAME}_prod'
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    restart: unless-stopped
    ports:
      - '${CONTAINER_PORT_PROD:-8081}:8080'
    networks:
      - go_network_app
    depends_on:
      - app_postgres
      - app_redis

  app_postgres:
    image: postgres:15.4
    container_name: app_postgres
    networks:
      - go_network_app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres #5slD9ziHCCwWSv1LX1jN
    volumes:
      - .database/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app_redis:
    image: redis:6.2-alpine
    container_name: app_redis
    networks:
      - go_network_app
    ports:
      - "6379:6379"
    volumes:
      - .database/redis:/data

networks:
  go_network_app:
    external: true